baseURL = "https://Auburn-University-Ethical-Hacking-Club.github.io/"
languageCode = "en-us"
title = "Auburn Ethical Hacking Club"
theme = "PaperMod"

paginate = 15

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.label]
  text = "Auburn Ethical Hacking Club"
  icon = "/images/ehc-logo.png"
  iconHeight = 40

[params.homeInfoParams]
  Title = "Auburn Ethical Hacking Club"
  Content = "CTF writeups, resources, and club updates."

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Constitution"
  url = "/constitution/"
  weight = 20

[[menu.main]]
  name = "Discord"
  url = "https://discord.com/invite/hYmnWPG"
  weight = 30

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/Auburn-University-Ethical-Hacking-Club"
  weight = 40

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/103816580/admin/dashboard/"
  weight = 50
